import {
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  Undo2,
  CornerUpLeft,
  CornerUpRight,
  LogIn,
  LogOut,
  ArrowDownToLine,
  ArrowUpToLine,
  RotateCcw,
  Ship,
  MapPin,
  Flag,
  ParkingCircle,
  type LucideIcon,
} from 'lucide-react';

export const NaviGuideType = {
  STRAIGHT: 0,
  LEFT_TURN: 1,
  RIGHT_TURN: 2,
  U_TURN: 3,
  KEEP_LEFT: 5,
  KEEP_RIGHT: 6,
  HIGHWAY_EXIT: 7,
  HIGHWAY_EXIT_LEFT: 8,
  HIGHWAY_EXIT_RIGHT: 9,
  HIGHWAY_ENTRANCE: 10,
  HIGHWAY_ENTRANCE_LEFT: 11,
  HIGHWAY_ENTRANCE_RIGHT: 12,
  OVERPASS: 14,
  UNDERPASS: 15,
  OVERPASS_SIDE: 16,
  UNDERPASS_SIDE: 17,
  ROTARY_1H: 30,
  ROTARY_2H: 31,
  ROTARY_3H: 32,
  FERRY_IN: 61,
  FERRY_OUT: 62,
  ROTARY_CIRCLE_1H: 70,
  ROTARY_CIRCLE_2H: 71,
  START: 100,
  END: 101,
  VIA: 1000,
  TOLLGATE: 300,
  SERVICE_AREA: 301,
};

export const NaviGuideIconMap: Record<number, LucideIcon> = {
  [NaviGuideType.STRAIGHT]: ArrowUp,
  [NaviGuideType.LEFT_TURN]: ArrowLeft,
  [NaviGuideType.RIGHT_TURN]: ArrowRight,
  [NaviGuideType.U_TURN]: Undo2,
  [NaviGuideType.KEEP_LEFT]: CornerUpLeft,
  [NaviGuideType.KEEP_RIGHT]: CornerUpRight,
  [NaviGuideType.HIGHWAY_ENTRANCE]: LogIn,
  [NaviGuideType.HIGHWAY_EXIT]: LogOut,
  [NaviGuideType.HIGHWAY_ENTRANCE_LEFT]: LogIn,
  [NaviGuideType.HIGHWAY_ENTRANCE_RIGHT]: LogIn,
  [NaviGuideType.HIGHWAY_EXIT_LEFT]: LogOut,
  [NaviGuideType.HIGHWAY_EXIT_RIGHT]: LogOut,
  [NaviGuideType.OVERPASS]: ArrowUpToLine,
  [NaviGuideType.UNDERPASS]: ArrowDownToLine,
  [NaviGuideType.OVERPASS_SIDE]: CornerUpRight,
  [NaviGuideType.UNDERPASS_SIDE]: CornerUpRight,
  [NaviGuideType.FERRY_IN]: Ship,
  [NaviGuideType.FERRY_OUT]: Ship,
  [NaviGuideType.START]: Flag,
  [NaviGuideType.END]: MapPin,
  [NaviGuideType.VIA]: MapPin,
  [NaviGuideType.SERVICE_AREA]: ParkingCircle,
  [NaviGuideType.ROTARY_1H]: RotateCcw,
  [NaviGuideType.ROTARY_2H]: RotateCcw,
  [NaviGuideType.ROTARY_3H]: RotateCcw,
  [NaviGuideType.ROTARY_CIRCLE_1H]: RotateCcw,
  [NaviGuideType.ROTARY_CIRCLE_2H]: RotateCcw,
};
